<<<<<<< HEAD
# Generated by Django 2.2.3 on 2020-04-12 13:32
=======
# Generated by Django 2.1.5 on 2020-04-13 11:39
>>>>>>> b0cfd62566f3807f99e8db9398a4c59c88900782

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CurrentPet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='eg.cute cat', max_length=128)),
                ('description', models.TextField(help_text='Tell something about the pet')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('image1', models.ImageField(default='pet_images/default.png', upload_to='pet_images')),
                ('image2', models.ImageField(blank=True, upload_to='pet_images')),
                ('image3', models.ImageField(blank=True, upload_to='pet_images')),
                ('image4', models.ImageField(blank=True, upload_to='pet_images')),
                ('image5', models.ImageField(blank=True, upload_to='pet_images')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=10)),
                ('description', models.TextField(help_text='Tell us something about you')),
                ('picture', models.ImageField(default='profile_images/default-user.png', upload_to='profile_images')),
                ('dob', models.DateField(null=True)),
                ('isGiver', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('date_reg', models.DateField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category')),
            ],
            options={
                'verbose_name_plural': 'subcategories',
=======
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pets', models.ManyToManyField(to='home.CurrentPet')),
            ],
        ),
        migrations.CreateModel(
            name='GivenPet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='eg.cute cat', max_length=128)),
                ('description', models.TextField(help_text='Tell something about the pet')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('image1', models.ImageField(default='pet_images/default.png', upload_to='pet_images')),
            ],
            options={
                'abstract': False,
>>>>>>> b0cfd62566f3807f99e8db9398a4c59c88900782
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Insert title here', max_length=128)),
                ('text', models.TextField(help_text='Tell us how the owner was')),
                ('on_date', models.DateField(auto_now_add=True, null=True)),
                ('rating', models.IntegerField()),
<<<<<<< HEAD
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='home.UserProfile')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed', to='home.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='GivenPet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='eg.cute cat', max_length=128)),
                ('description', models.TextField(help_text='Tell something about the pet')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('image1', models.ImageField(default='pet_images/default.png', upload_to='pet_images')),
                ('adopter', models.ForeignKey(on_delete=models.SET('This user no longer exists'), related_name='adopter', to='home.UserProfile')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Category')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_by', to='home.UserProfile')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pets', models.ManyToManyField(to='home.CurrentPet')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.UserProfile')),
            ],
        ),
        migrations.AddField(
=======
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category')),
            ],
            options={
                'verbose_name_plural': 'subcategories',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=10)),
                ('description', models.TextField(help_text='Tell us something about you')),
                ('picture', models.ImageField(default='profile_images/default-user.png', upload_to='profile_images')),
                ('dob', models.DateField(null=True)),
                ('isGiver', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('date_reg', models.DateField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='adopter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='home.UserProfile'),
        ),
        migrations.AddField(
            model_name='review',
            name='giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed', to='home.UserProfile'),
        ),
        migrations.AddField(
            model_name='givenpet',
            name='adopter',
            field=models.ForeignKey(on_delete=models.SET('This user no longer exists'), related_name='adopter', to='home.UserProfile'),
        ),
        migrations.AddField(
            model_name='givenpet',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Category'),
        ),
        migrations.AddField(
            model_name='givenpet',
            name='giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_by', to='home.UserProfile'),
        ),
        migrations.AddField(
            model_name='givenpet',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Subcategory'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.UserProfile'),
        ),
        migrations.AddField(
>>>>>>> b0cfd62566f3807f99e8db9398a4c59c88900782
            model_name='currentpet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='home.UserProfile'),
        ),
        migrations.AddField(
            model_name='currentpet',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Subcategory'),
        ),
    ]
